### ISSUE TITLE
Api key

### ISSUE THREAD

**Issue by anshupal257** [nicoqueijo/Android-Currency-Converter#4]
from where can i get the api key

and RowSelectableCurrencyBinding could not be found

**Comment by nicoqueijo** [comment]
In the project the api key is being retrieved from a file called secrets.xml which is not being tracked by git for obvious reasons. You can get your own api key [here](https://openexchangerates.org/). As far as RowSelectableCurrencyBinding you might want to clean and rebuild the project. If that doesn't work try selecting "Invalidate Caches / Restart" under File in Android Studio.
